### ISSUE TITLE
好像不支持Baiduwp-PHP 4.0.3？

### ISSUE THREAD

**Issue by jisa8438** [z-mio/baiduwp-bot#4]
好像不支持Baiduwp-PHP 4.0.3？

**Comment by lsyyktv** [comment]
> 像不支持Baiduwp-PHP 4.0.3？

前段时间我更新到4.0.3,然后bot就没反应了，退回3.0.2又好了。
我再试试看吧，谢谢！

**Comment by lsyyktv** [comment]
> 适配的

拉取最新源码解决了，感谢！
