### ISSUE TITLE
发现一个倒霉蛋

### ISSUE THREAD

**Issue by cinitdev** [z-mio/baiduwp-bot#7]
![Screenshot_2024-02-13-14-42-22-258_org telegram messenger](https://github.com/z-mio/baiduwp-bot/assets/78637344/4e860585-02d1-4050-bfba-4343752eba68)
![Screenshot_2024-02-13-14-42-35-102_org telegram messenger](https://github.com/z-mio/baiduwp-bot/assets/78637344/d73d31e7-8b60-4e3a-bbbb-b29897f674db)
![Screenshot_2024-02-13-14-42-42-118_org telegram messenger](https://github.com/z-mio/baiduwp-bot/assets/78637344/5d99546b-501b-4f53-9df3-7c85d80de4b6)
![Screenshot_2024-02-13-14-42-48-613_org telegram messenger](https://github.com/z-mio/baiduwp-bot/assets/78637344/ffbea5b9-34f0-485d-b069-5288e78c51c5)
🤣

**Comment by z-mio** [comment]
![2024_02_13_14_51_09_182](https://github.com/z-mio/baiduwp-bot/assets/52116367/b3cea7e9-7c29-4bb9-bdbc-77255ba6c7fd)
