### ISSUE TITLE
大佬，今天开始网盘解析一直错误超时

### ISSUE THREAD

**Issue by Tigerking87** [z-mio/baiduwp-bot#8]

**Comment by z-mio** [comment]
自己部署的吗,还是 @getletbot
@getletbot的话晚点再修

**Comment by Tigerking87** [comment]
大佬，今天出现问题了：普通账号 Cookie 状态异常，请检查：账号是否被限制、Cookie 是否过期，是不是我下载太多导致账户被封了呢
